### ISSUE TITLE
Local Tests Failing Because of "Quick" error?

### ISSUE THREAD

**Issue by Richel325** [learn-co-curriculum/swift-functionFun-lab#2]
Hi,

I ran the local tests on this lab, and all the answers seem correct (I tested them in a playground first to make sure), but I still keep getting an error after the build fails because of the top line that says "Import Quick". The error is "No such module 'Quick'". Anybody having this issue as well?

When I try to delete that line from the test, a ton of other errors pop up...so I'm not sure what I'm doing wrong. Please help if you can, thanks!
![screen shot 2016-08-12 at 4 49 14 pm](https://cloud.githubusercontent.com/assets/19737897/17636890/31c44b22-60ae-11e6-9b38-1ea5b246c233.png)

Richel

**Comment by JimCampagno** [comment]
@Richel325 This should be fixed. Let me know if you're still having any issues. Closing this right now (as I was able to get it to work on my end). Feel free to open up another issue if you find it's doing the same thing on your end. 

Make sure to be hitting command + u to get the test to run and build.

If that's not working. Also look to hit command + b (which builds your project) before then hitting command + u (which will run the tests.
