### ISSUE TITLE
Issue/Error with Lab - thanks for your help and looking into this!

### ISSUE THREAD

**Issue by Richel325** [learn-co-curriculum/swift-functionFun-lab#3]
Per my question on Learn and issue raised by other students. 
![screen shot 2016-08-16 at 5 04 15 pm](https://cloud.githubusercontent.com/assets/19737897/17716189/a36de8c6-63d5-11e6-984d-f15f08e0faae.png)
![screen shot 2016-08-16 at 5 03 58 pm](https://cloud.githubusercontent.com/assets/19737897/17716196/a616b648-63d5-11e6-8a0d-e2aa02bb5e4b.png)
![screen shot 2016-08-16 at 5 04 02 pm](https://cloud.githubusercontent.com/assets/19737897/17716198/a77efbb2-63d5-11e6-9d69-a05f564222f8.png)

**Comment by AnnJohn** [comment]
hi @Richel325 i'm going to close this issue since it looks similar to another one that was already  raised. Going forward, however, could you please explain what the issue you have is in addition to posting screenshots. thanks
