### ISSUE TITLE
Tests Keep Running

### ISSUE THREAD

**Issue by tjcarney89** [learn-co-curriculum/swift-functionFun-lab#5]
I've completed the functions and the build is successful with no errors. However, it just keeps saying it is, "Testing FunctionFun Tests." I waited a few hours and it still is in the same spot. I can't seem to move on until the tests actually pass. 

Any help would be appreciated!

Thanks!

TJ

**Comment by JimCampagno** [comment]
@tjcarney89 I'm very late in responding to this. But thanks for raising this issue.

I just completely re-wrote this lab from the ground up. It's working perfectly (at least on my end!). If you want to re-attempt this lab, then I suggest re-cloning it down (similar to the advice I gave you on the other lab). I'll include a link to the video on how to do that again which you can find [here](https://youtu.be/CsMDUFyyiNI).

Keep crushing it! 👍
